### ISSUE TITLE
Cannot find 'tsconfig.json'

### ISSUE THREAD

**Issue by Roanmh** [yrming/vscode-type-challenges#12]
I installed the extension for the first time and it seemed to work. At some point after opening some files, and choosing to save files to `~/.typeChallenges`, the 'Take the challenge' button stopped working. I tried reinstalling the app and reloading VSCode and restarting my computer. After the reinstall, the extension side-bar does not work. Two symptoms in this state are:

1. Opening the extension side-bar results in multiple errors and warnings: (viewable in the developer console)

```
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: ENOENT: no such file or directory, copyfile '/Users/haydenr/.vscode/extensions/yrm.type-challenges-1.7.0/resources/tsconfig.json' -> '/Users/haydenr/.typeChallenges/tsconfig.json'
console.ts:137 [Extension Host] stack trace: Error: ENOENT: no such file or directory, copyfile '/Users/haydenr/.vscode/extensions/yrm.type-challenges-1.7.0/resources/tsconfig.json' -> '/Users/haydenr/.typeChallenges/tsconfig.json'
    at Object.copyFileSync (node:fs:2804:3)
    at Object.func [as copyFileSync] (node:electron/js2c/asar_bundle:5:1812)
    at createTsConfigFile (/Users/haydenr/.vscode/extensions/yrm.type-challenges-1.7.0/out/utils/questions.js:202:13)
    at getAllQuestions (/Users/haydenr/.vscode/extensions/yrm.type-challenges-1.7.0/out/utils/questions.js:13:5)
    at registerTrees (/Users/haydenr/.vscode/extensions/yrm.type-challenges-1.7.0/out/tree/registerTrees.js:10:26)
log.ts:313 ERR ENOENT: no such file or directory, copyfile ERR ENOENT: no such file or directory, copyfile '/Users/haydenr/.vscode/extensions/yrm.type-challenges-1.7.0/resources/tsconfig.json' -> '/Users/haydenr/.typeChallenges/tsconfig.json': Error: ENOENT: no such file or directory, copyfile '/Users/haydenr/.vscode/extensions/yrm.type-challenges-1.7.0/resources/tsconfig.json' -> '/Users/haydenr/.typeChallenges/tsconfig.json'
    at Object.copyFileSync (node:fs:2804:3)
    at Object.func [as copyFileSync] (node:electron/js2c/asar_bundle:5:1812)
    at createTsConfigFile (/Users/haydenr/.vscode/extensions/yrm.type-challenges-1.7.0/out/utils/questions.js:202:13)
    at getAllQuestions (/Users/haydenr/.vscode/extensions/yrm.type-challenges-1.7.0/out/utils/questions.js:13:5)
    at registerTrees (/Users/haydenr/.vscode/extensions/yrm.type-challenges-1.7.0/out/tree/registerTrees.js:10:26)
```

3. Pressing the refresh button of the side-bar results in this error:

```
notificationsAlerts.ts:40 Error: command 'typeChallenges.refresh' not found
    at S._tryExecuteCommand (commandService.ts:91:26)
    at S.executeCommand (commandService.ts:85:15)
    at async k.runAction (actions.ts:192:3)
    at async k.run (actions.ts:183:4)
    at async g.onClick (menuEntryActionViewItem.ts:152:4)
```

When I chose to save results to `~/.typeChallenges` it created the directory and put 2 files inside: `00007-easy-readonly.ts` and `test-utils.ts`

Thanks,
Roan

**Comment by yrming** [comment]
@Roanmh Thank you very much for your issue, now this bug has been fixed and you can update to the latest version.😃
